# Generated by Django 3.1.5 on 2021-01-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daerah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=13)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
    ]
